// <auto-generated />
using System;
using Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_interests");

                    b.ToTable("interests", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("By")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("by");

                    b.Property<int>("Descendants")
                        .HasColumnType("integer")
                        .HasColumnName("descendants");

                    b.PrimitiveCollection<int[]>("Kids")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("kids");

                    b.Property<double>("Rank")
                        .HasColumnType("double precision")
                        .HasColumnName("rank");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("Time")
                        .HasColumnType("integer")
                        .HasColumnName("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_stories");

                    b.ToTable("stories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.Property<int>("InterestedUsersId")
                        .HasColumnType("integer")
                        .HasColumnName("interested_users_id");

                    b.Property<int>("InterestsId")
                        .HasColumnType("integer")
                        .HasColumnName("interests_id");

                    b.HasKey("InterestedUsersId", "InterestsId")
                        .HasName("pk_interest_user");

                    b.HasIndex("InterestsId")
                        .HasDatabaseName("ix_interest_user_interests_id");

                    b.ToTable("interest_user", (string)null);
                });

            modelBuilder.Entity("StoryTag", b =>
                {
                    b.Property<int>("StoriesId")
                        .HasColumnType("integer")
                        .HasColumnName("stories_id");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer")
                        .HasColumnName("tags_id");

                    b.HasKey("StoriesId", "TagsId")
                        .HasName("pk_story_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_story_tag_tags_id");

                    b.ToTable("story_tag", (string)null);
                });

            modelBuilder.Entity("StoryUser", b =>
                {
                    b.Property<int>("FavouriteStoriesId")
                        .HasColumnType("integer")
                        .HasColumnName("favourite_stories_id");

                    b.Property<int>("FavouritedById")
                        .HasColumnType("integer")
                        .HasColumnName("favourited_by_id");

                    b.HasKey("FavouriteStoriesId", "FavouritedById")
                        .HasName("pk_story_user");

                    b.HasIndex("FavouritedById")
                        .HasDatabaseName("ix_story_user_favourited_by_id");

                    b.ToTable("story_user", (string)null);
                });

            modelBuilder.Entity("InterestUser", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InterestedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interest_user_users_interested_users_id");

                    b.HasOne("Domain.Entities.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interest_user_interests_interests_id");
                });

            modelBuilder.Entity("StoryTag", b =>
                {
                    b.HasOne("Domain.Entities.Story", null)
                        .WithMany()
                        .HasForeignKey("StoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_tag_stories_stories_id");

                    b.HasOne("Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_tag_tags_tags_id");
                });

            modelBuilder.Entity("StoryUser", b =>
                {
                    b.HasOne("Domain.Entities.Story", null)
                        .WithMany()
                        .HasForeignKey("FavouriteStoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_user_stories_favourite_stories_id");

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FavouritedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_user_users_favourited_by_id");
                });
#pragma warning restore 612, 618
        }
    }
}
