name: Deploy
on: 
  push:
    branches: 
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Heroku
      run: |
        docker login --username=${{ secrets.USERNAME }} --password=${{ secrets.HEROKU_DEPLOY_API_KEY }} registry.heroku.com
        heroku container:push web -a "hn-stories-feed"
        heroku container:release web -a "hn-stories-feed"
