name: build-and-test
on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          HackerNewsCommentsFeed/
          Application/
          Domain/
          Infrastructure/
          Shared/
          Tests/
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: artifacts/
      
    - name: Test
      working-directory: artifacts/Tests/
      run: dotnet restore && dotnet test --no-build --verbosity normal
