name: test
on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
    
    - name: Print directories
      run: ls -a
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: src
        path: HackerNewsCommentsFeed/bin/Debug
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: HackerNewsCommentsFeed/bin/Debug
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: HackerNewsCommentsFeed/bin/Debug/net6.0
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
