name: build-and-test
on: push
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: src/
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: artifacts/
      
    - name: Display current path
      working-directory: artifacts/
      run: ls -a && pwd
      
    - name: Test
      working-directory: artifacts/
      run: pwd && ls -a && dotnet test --no-build --verbosity normal
